client_config_backend: settings
client_config:
  client_id: 1033452540986-9sfqueasb12v3ll4rn6l8m517ebvjdut.apps.googleusercontent.com
  client_secret: unknown
  auth_url: https://accounts.google.com/o/oauth2/auth?access_type=offline
  redirect_uri: urn:ietf:wg:oauth:2.0:oob
  token_uri: https://oauth2.googleapis.com/token
  
save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - email
  - profile
